workspace:
  base: /go
  path: src/github.com/peoplenet/terraform-instaclustr-provider
  
pipeline:
  build:
    image: golang:1.8.0-alpine
    commands:
      - go vet .
      - go test .
      - go build -o terraform-provider-instaclustr
      - tar -zcvf terraform-provider-instaclustr-linux-amd64.tar.gz terraform-provider-instaclustr

  s3:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: ${PN_AWS_ACCESS_KEY_ID}
    secret_key: ${PN_AWS_SECRET_ACCESS_KEY}
    source: terraform-provider-instaclustr-linux-amd64.tar.gz
    target: /terraform-provider-instaclustr
    when:
      local: false
      branch: master
