workspace:
  base: /go
  path: src/github.com/peoplenet/terraform-instaclustr-provider
branches: [ master, feature/* ]
pipeline:
  version:
    image: alpine/git
    commands:
      - git fetch --tags
      - git describe --tags > version
  build:
    image: golang:1.9.0-alpine
    commands:
      - VERSION=$(cat version)
      - echo $VERSION
      - apk --no-cache add zip
      - go vet .
      - CGO_ENABLED=0 GOOS=linux go build -installsuffix cgo -o terraform-provider-instaclustr_v$VERSION
      - zip terraform-provider-instaclustr-$VERSION-linux-amd64.zip terraform-provider-instaclustr_v$VERSION
      - rm terraform-provider-instaclustr_v$VERSION
      - GOOS=darwin go build -o terraform-provider-instaclustr_v$VERSION
      - zip terraform-provider-instaclustr-$VERSION-darwin-amd64.zip terraform-provider-instaclustr_v$VERSION
    environment:
      - INSTACLUSTR_ACCESS_KEY=${INSTACLUSTR_ACCESS_KEY}
      - INSTACLUSTR_SECRET_KEY=${INSTACLUSTR_SECRET_KEY}

  s3:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: ${PN_AWS_ACCESS_KEY_ID}
    secret_key: ${PN_AWS_SECRET_ACCESS_KEY}
    source: terraform-provider-instaclustr-*.zip
    target: /terraform-provider-instaclustr
    when:
      local: false
      event: tag

