pipeline:
  build:
      image: golang
      commands:
        - go build -o terraform-provider-instaclustr
        - tar -zcvf terraform-provider-instaclustr-linux-amd64.tar.gz terraform-provider-instaclustr


  publish:
    s3:
      acl: authenticated-read
      region: "us-east-1"
      bucket: "peoplenet-custom-tools"
      access_key: ${PN_AWS_ACCESS_KEY_ID}
      secret_key: ${PN_AWS_SECRET_ACCESS_KEY}
      source: terraform-provider-instaclustr-linux-amd64.tar.gz
      target: /terraform-provider-instaclustr/terraform-provider-instaclustr-linux-amd64.tar.gz
      when:
        branch: master
