workspace:
  base: /go
  path: src/github.com/peoplenet/terraform-instaclustr-provider
branches: [ master, feature/* ]
pipeline:
  build:
    image: golang:1.9.0-alpine
    commands:
      - go vet .
      - GOOS=linux go build -o terraform-provider-instaclustr
      - file terraform-provider-instaclustr
      - tar -zcvf terraform-provider-instaclustr-linux-amd64.tar.gz terraform-provider-instaclustr
      - rm terraform-provider-instaclustr
      - GOOS=darwin go build -o terraform-provider-instaclustr
      - file terraform-provider-instaclustr
      - tar -zcvf terraform-provider-instaclustr-darwin-amd64.tar.gz terraform-provider-instaclustr
    environment:
      - INSTACLUSTR_ACCESS_KEY=${INSTACLUSTR_ACCESS_KEY}
      - INSTACLUSTR_SECRET_KEY=${INSTACLUSTR_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${PN_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${PN_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1

  s3:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: ${PN_AWS_ACCESS_KEY_ID}
    secret_key: ${PN_AWS_SECRET_ACCESS_KEY}
    source: terraform-provider-instaclustr-linux-amd64.tar.gz
    target: /terraform-provider-instaclustr
    when:
      local: false
      branch: master
  s3:
    image: plugins/s3
    acl: public-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: ${PN_AWS_ACCESS_KEY_ID}
    secret_key: ${PN_AWS_SECRET_ACCESS_KEY}
    source: terraform-provider-instaclustr-darwin-amd64.tar.gz
    target: /terraform-provider-instaclustr
    when:
      local: false
      branch: master
